/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryCreateDataDto } from '../../models/category-create-data-dto';

export interface GetCategoryCreateData$Params {
}

export function getCategoryCreateData(http: HttpClient, rootUrl: string, params?: GetCategoryCreateData$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryCreateDataDto>> {
  const rb = new RequestBuilder(rootUrl, getCategoryCreateData.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryCreateDataDto>;
    })
  );
}

getCategoryCreateData.PATH = '/api/category/createData';
