/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryDetailedDto } from '../../models/category-detailed-dto';

export interface GetMainCategories$Params {
}

export function getMainCategories(http: HttpClient, rootUrl: string, params?: GetMainCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryDetailedDto>>> {
  const rb = new RequestBuilder(rootUrl, getMainCategories.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryDetailedDto>>;
    })
  );
}

getMainCategories.PATH = '/api/category/main';
