import {ProductResponse} from "../api/models/product-response";

export const testProducts: ProductResponse[] = [
  {
    id:'abc0',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc1',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc2',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc3',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc4',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc5',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  },
  {
    id:'abc6',
    brand:'Armani',
    category: 'Öltözet',
    count:12,
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eros velit, pellentesque non ex non, faucibus tempor nisl. Ut eu ante non dolor mollis molestie. Donec turpis mi, tempor ac finibus at, dapibus ac est. Aliquam at nisi diam. Suspendisse tristique laoreet sem, non facilisis enim fringilla eu. Mauris tristique tristique viverra. Ut imperdiet eros eget enim molestie, id lobortis justo elementum. Nulla ut efficitur urna. Sed et ipsum quis velit viverra ornare ut at leo. Curabitur eget bibendum nulla. Pellentesque sapien quam, elementum vel risus vitae, dignissim vehicula tortor.\nUt a magna ante. Ut nulla sem, feugiat at egestas in, ultrices in lectus. Sed laoreet nulla eros, et ullamcorper arcu eleifend quis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum faucibus pulvinar iaculis.',
    name:'Kabát',
    price:244999,
    type:'Kabát',
    subCategory:'Dzseki',
  }
]
