/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOrderDto } from '../../models/page-order-dto';

export interface GetOrderListPage$Params {
  status?: 'CANCELLED' | 'CREATED' | 'IN_PROGRESS' | 'UNDER_DELIVERY' | 'COMPLETED';
  id?: number;
  page?: number;
  size?: number;
  sortId?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getOrderListPage(http: HttpClient, rootUrl: string, params?: GetOrderListPage$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOrderDto>> {
  const rb = new RequestBuilder(rootUrl, getOrderListPage.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('id', params.id, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortId', params.sortId, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOrderDto>;
    })
  );
}

getOrderListPage.PATH = '/api/order/list';
