/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CartElementDto } from '../../models/cart-element-dto';

export interface ChangeQuantity$Params {
  id: number;
  quantity: number;
}

export function changeQuantity(http: HttpClient, rootUrl: string, params: ChangeQuantity$Params, context?: HttpContext): Observable<StrictHttpResponse<CartElementDto>> {
  const rb = new RequestBuilder(rootUrl, changeQuantity.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('quantity', params.quantity, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CartElementDto>;
    })
  );
}

changeQuantity.PATH = '/api/cart/{id}/modify/{quantity}';
