/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {
  city?: string;
  country?: string;
  number?: string;
  postalCode?: string;
  street?: string;
}
