/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductDto } from '../models/product-dto';
export interface CartElementDto {
  id: number;
  productDto: ProductDto;
  quantity: number;
}
