/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryDto {
  id: number;
  name?: string;
  parentCategoryId?: number;
  subCategoryIds?: Array<number>;
}
