/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryDto } from '../models/category-dto';
export interface CategoryCreateDataDto {
  childCategories?: Array<CategoryDto>;
  parentCategories?: Array<CategoryDto>;
}
