/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryBasicDto } from '../models/category-basic-dto';
export interface CategoryDetailedDto {
  id: number;
  name?: string;
  subCategories?: Array<CategoryBasicDto>;
}
