/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { OrderItemDto } from '../models/order-item-dto';
export interface OrderDto {
  billingAddress?: Address;
  id?: number;
  items?: Array<OrderItemDto>;
  shippingAddress?: Address;
  status?: 'CREATED' | 'IN_PROGRESS' | 'UNDER_DELIVERY' | 'COMPLETED';
}
