/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { OrderItemDto } from '../models/order-item-dto';
import { UserDto } from '../models/user-dto';
export interface OrderDto {
  billingAddress: Address;
  date: string;
  id: number;
  items: Array<OrderItemDto>;
  shippingAddress: Address;
  status: 'CANCELLED' | 'CREATED' | 'IN_PROGRESS' | 'UNDER_DELIVERY' | 'COMPLETED';
  user: UserDto;
}
