/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface OrderCreateDto {
  billingAddress: Address;
  shippingAddress: Address;
}
