/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BrandDto } from '../models/brand-dto';
import { CategoryDto } from '../models/category-dto';
export interface ProductDto {
  brand?: BrandDto;
  category?: CategoryDto;
  count?: number;
  description?: string;
  discountPercentage?: number;
  id: number;
  images?: Array<string>;
  name?: string;
  price?: number;
}
