/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductCreateDto {
  brandId?: number;
  categoryId?: number;
  count?: number;
  description?: string;
  discountPercentage?: number;
  name?: string;
  price?: number;
}
