/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageModifyDto } from '../models/image-modify-dto';
export interface ProductModifyDto {
  brandId?: number;
  categoryId?: number;
  count?: number;
  description?: string;
  discountPercentage?: number;
  id?: number;
  images?: Array<ImageModifyDto>;
  name?: string;
  price?: number;
}
