/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface UserCreateDto {
  address?: Address;
  email?: string;
  firstName?: string;
  gender?: 'MALE' | 'FEMALE';
  id?: string;
  lastName?: string;
  password?: string;
  role?: 'ADMIN' | 'USER' | 'SUPER_ADMIN';
}
