/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { CartElementDto } from '../models/cart-element-dto';
import { ProductDto } from '../models/product-dto';
export interface UserDtoDetailed {
  address?: Address;
  cartItems?: Array<CartElementDto>;
  email?: string;
  firsName?: string;
  gender?: 'MALE' | 'FEMALE';
  id?: string;
  lastName?: string;
  phone?: string;
  role?: 'ADMIN' | 'USER' | 'SUPER_ADMIN';
  savedItems?: Array<ProductDto>;
}
