/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface UserDto {
  address?: Address;
  cartNumber?: number;
  email?: string;
  firsName?: string;
  gender?: 'MALE' | 'FEMALE';
  id?: string;
  lastName?: string;
  phone?: string;
  role?: 'ADMIN' | 'USER' | 'SUPER_ADMIN';
  savedNumber?: number;
}
