/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface UserModifyDto {
  address?: Address;
  email?: string;
  firstName?: string;
  gender?: 'MALE' | 'FEMALE';
  lastName?: string;
  phone?: string;
}
