/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BrandDto } from '../models/brand-dto';
import { createBrand } from '../fn/brand-controller/create-brand';
import { CreateBrand$Params } from '../fn/brand-controller/create-brand';
import { deleteBrand } from '../fn/brand-controller/delete-brand';
import { DeleteBrand$Params } from '../fn/brand-controller/delete-brand';
import { getBrandById } from '../fn/brand-controller/get-brand-by-id';
import { GetBrandById$Params } from '../fn/brand-controller/get-brand-by-id';
import { getBrandList } from '../fn/brand-controller/get-brand-list';
import { GetBrandList$Params } from '../fn/brand-controller/get-brand-list';
import { modifyBrand } from '../fn/brand-controller/modify-brand';
import { ModifyBrand$Params } from '../fn/brand-controller/modify-brand';
import { modifyBrand1 } from '../fn/brand-controller/modify-brand-1';
import { ModifyBrand1$Params } from '../fn/brand-controller/modify-brand-1';

@Injectable({ providedIn: 'root' })
export class BrandControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `modifyBrand()` */
  static readonly ModifyBrandPath = '/api/brand/modify';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `modifyBrand()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modifyBrand$Response(params: ModifyBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
    return modifyBrand(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `modifyBrand$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modifyBrand(params: ModifyBrand$Params, context?: HttpContext): Observable<BrandDto> {
    return this.modifyBrand$Response(params, context).pipe(
      map((r: StrictHttpResponse<BrandDto>): BrandDto => r.body)
    );
  }

  /** Path part for operation `modifyBrand1()` */
  static readonly ModifyBrand1Path = '/api/brand/modifyImage/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `modifyBrand1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modifyBrand1$Response(params: ModifyBrand1$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
    return modifyBrand1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `modifyBrand1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modifyBrand1(params: ModifyBrand1$Params, context?: HttpContext): Observable<BrandDto> {
    return this.modifyBrand1$Response(params, context).pipe(
      map((r: StrictHttpResponse<BrandDto>): BrandDto => r.body)
    );
  }

  /** Path part for operation `createBrand()` */
  static readonly CreateBrandPath = '/api/brand/create';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBrand()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBrand$Response(params: CreateBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
    return createBrand(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBrand$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBrand(params: CreateBrand$Params, context?: HttpContext): Observable<BrandDto> {
    return this.createBrand$Response(params, context).pipe(
      map((r: StrictHttpResponse<BrandDto>): BrandDto => r.body)
    );
  }

  /** Path part for operation `getBrandById()` */
  static readonly GetBrandByIdPath = '/api/brand/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBrandById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBrandById$Response(params: GetBrandById$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
    return getBrandById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBrandById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBrandById(params: GetBrandById$Params, context?: HttpContext): Observable<BrandDto> {
    return this.getBrandById$Response(params, context).pipe(
      map((r: StrictHttpResponse<BrandDto>): BrandDto => r.body)
    );
  }

  /** Path part for operation `getBrandList()` */
  static readonly GetBrandListPath = '/api/brand/list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getBrandList()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBrandList$Response(params?: GetBrandList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BrandDto>>> {
    return getBrandList(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getBrandList$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getBrandList(params?: GetBrandList$Params, context?: HttpContext): Observable<Array<BrandDto>> {
    return this.getBrandList$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BrandDto>>): Array<BrandDto> => r.body)
    );
  }

  /** Path part for operation `deleteBrand()` */
  static readonly DeleteBrandPath = '/api/brand/delete/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteBrand()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBrand$Response(params: DeleteBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return deleteBrand(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteBrand$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteBrand(params: DeleteBrand$Params, context?: HttpContext): Observable<boolean> {
    return this.deleteBrand$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
