/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandCreateDto } from '../../models/brand-create-dto';
import { BrandDto } from '../../models/brand-dto';

export interface CreateBrand$Params {
      body?: {
'brand': BrandCreateDto;
'image': Blob;
}
}

export function createBrand(http: HttpClient, rootUrl: string, params?: CreateBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
  const rb = new RequestBuilder(rootUrl, createBrand.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BrandDto>;
    })
  );
}

createBrand.PATH = '/api/brand/create';
