/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandSimpleDto } from '../../models/brand-simple-dto';

export interface GetBrands$Params {
}

export function getBrands(http: HttpClient, rootUrl: string, params?: GetBrands$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BrandSimpleDto>>> {
  const rb = new RequestBuilder(rootUrl, getBrands.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BrandSimpleDto>>;
    })
  );
}

getBrands.PATH = '/api/brand';
