/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandDto } from '../../models/brand-dto';

export interface GetBrandList$Params {
}

export function getBrandList(http: HttpClient, rootUrl: string, params?: GetBrandList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BrandDto>>> {
  const rb = new RequestBuilder(rootUrl, getBrandList.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BrandDto>>;
    })
  );
}

getBrandList.PATH = '/api/brand/list';
