/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageBrandDto } from '../../models/page-brand-dto';

export interface GetBrandPageable$Params {
  name?: string;
  page?: number;
  size?: number;
  sortId?: string;
  sortDirection?: 'ASC' | 'DESC';
}

export function getBrandPageable(http: HttpClient, rootUrl: string, params?: GetBrandPageable$Params, context?: HttpContext): Observable<StrictHttpResponse<PageBrandDto>> {
  const rb = new RequestBuilder(rootUrl, getBrandPageable.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortId', params.sortId, {});
    rb.query('sortDirection', params.sortDirection, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageBrandDto>;
    })
  );
}

getBrandPageable.PATH = '/api/brand/list';
