/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BrandDto } from '../../models/brand-dto';

export interface ModifyBrand$Params {
      body: BrandDto
}

export function modifyBrand(http: HttpClient, rootUrl: string, params: ModifyBrand$Params, context?: HttpContext): Observable<StrictHttpResponse<BrandDto>> {
  const rb = new RequestBuilder(rootUrl, modifyBrand.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BrandDto>;
    })
  );
}

modifyBrand.PATH = '/api/brand/modify';
