/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDtoDetailed } from '../../models/user-dto-detailed';
import { UserModifyDto } from '../../models/user-modify-dto';

export interface ModifyUser$Params {
      body: UserModifyDto
}

export function modifyUser(http: HttpClient, rootUrl: string, params: ModifyUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDtoDetailed>> {
  const rb = new RequestBuilder(rootUrl, modifyUser.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserDtoDetailed>;
    })
  );
}

modifyUser.PATH = '/api/user/modify';
